bug fixes

diff --git a/000-makebins/clean b/000-makebins/clean
--- a/000-makebins/clean
+++ b/000-makebins/clean
@@ -1,2 +1,23 @@
-rm -rf ./bin
-rm -rf ./source
+source ../confparams.sh
+
+result=0
+echo
+echo -e "${FFS_YEL}############################################${FFS_NOC}"
+echo -e "${FFS_YEL} Cleaning the result of make bins procedure ${FFS_NOC}"
+echo -e "${FFS_BLU} Script :${FFS_NOC}" "$0"
+echo -e "${FFS_YEL}############################################${FFS_NOC}"
+echo "GOPATH         = "$GOPATH
+echo "FFS_FABRIC_BIN = "$FFS_FABRIC_BIN
+
+# rm $GOPATH only if it is defined in current dir. We need to be careful when removing $GOPATH ;)
+DTR=`echo $GOPATH | sed "s!$PWD!.!g"`
+test -d $DTR &&            bash -c "echo Removing dir $DTR located in $PWD; rm -rf $DTR" 
+test -d $FFS_FABRIC_BIN && bash -c "echo Removing $FFS_FABRIC_BIN; rm -rf $FFS_FABRIC_BIN"
+
+if [[ .$result. == .0. ]]; then
+        echo -e "Script result: ${FFS_GRE}SUCCESS${FFS_NOC}"
+else
+        echo -e "Script result: ${FFS_RED}FAILED${FFS_NOC}"
+fi
+
+exit $result
diff --git a/001-generateArtifacts/clean b/001-generateArtifacts/clean
--- a/001-generateArtifacts/clean
+++ b/001-generateArtifacts/clean
@@ -1,4 +1,25 @@
+source ../confparams.sh
+
+result=0
+echo
+echo -e "${FFS_YEL}###############################${FFS_NOC}"
+echo -e "${FFS_YEL} Cleaning all crypto artifacts ${FFS_NOC}"
+echo -e "${FFS_BLU} Script :${FFS_NOC}" "$0"
+echo -e "${FFS_YEL}###############################${FFS_NOC}"
+echo "GOPATH         = "$GOPATH
+
+set -x
 rm -rf artifacts
 rm configtx.yaml
 rm -rf crypto-config
 rm crypto-config.yaml
+set +x
+
+if [[ .$result. == .0. ]]; then
+        echo -e "Script result: ${FFS_GRE}SUCCESS${FFS_NOC}"
+else
+        echo -e "Script result: ${FFS_RED}FAILED${FFS_NOC}"
+fi
+
+exit $result
+
diff --git a/001-generateArtifacts/go b/001-generateArtifacts/go
--- a/001-generateArtifacts/go
+++ b/001-generateArtifacts/go
@@ -1,7 +1,16 @@
-set -e
-./s01.gencryptoconfig
-./s02.mkcrypto
-./s03.gentxconf
-./s04.mkgenesis
-./s05.chconftx
-./s06.anchorupdtx
+source ../confparams.sh
+result=0
+./s01.gencryptoconfig; (( result = result + $? ))
+./s02.mkcrypto; (( result = result + $? ))
+./s03.gentxconf; (( result = result + $? ))
+./s04.mkgenesis; (( result = result + $? ))
+./s05.chconftx; (( result = result + $? ))
+./s06.anchorupdtx; (( result = result + $? ))
+
+if [[ .$result. == .0. ]]; then
+        echo -e "Section result: ${FFS_GRE}SUCCESS${FFS_NOC}"
+	exit 0
+else
+        echo -e "Section result: ${FFS_RED}FAILED${FFS_NOC}"
+	exit 1
+fi
